[theme]
primaryColor = "#146C94"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3F7FA"
textColor = "#172B3A"
font = "sans serif"

[server]
headless = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
